### ISSUE TITLE
Is writeback mode stable or not

### ISSUE THREAD

**Issue by samuelxhu** [lanconnected/EnhanceIO#7]
I have read somewhere on the internet (don't remember exactly where) claiming that enhanceIO may loss data under some circumstances. Hence my question is 

1) Does someone here ever use enhanceio writeback cache mode in production, and how about reliability?
2) For how long?

I am planing to use enhanceio as the cache solution below Gluster bricks.

**Comment by onlyjob** [comment]
I only used EnhanceIO for read caching (safe). 
For write caching I would use [dm-writeboost](https://github.com/akiradeveloper/dm-writeboost) which is more robust.

**Comment by samuelxhu** [comment]
@onlyjob Very interesting information. Just wonder whether or not you still use EnhanceIO for read cache, because AFAIK dm-writeboot can be configured as combined read-and-write cache as well.

Should i focus on dm-writeboost only, or still there is a good reason for EnhanceIO as read cache?

**Comment by onlyjob** [comment]
I don't use EnhanceIO any more. I found read performance acceptable once write stress is relieved by _dm-writeboost_ or by ext4 external journal. Also in context of distributed parallel storage read caching is not very effective due to highly randomised access...

**Comment by samuelxhu** [comment]
@onlyjob I just looked around by googling but not able to find much information on dm-writeboost. Thus i turn to you for further clarification. 

1) In your view, is dm-writeboost stable enough for production? I see it use rambuf to aggregate multiple writes before flushing to SSD, so it relies much on the correctness of barrier/flush commands from the upper software layer, otherwise there may be data loss, right?
2) Do you use dm-writeboost in production your self? for howlong? It says quite a lot when there are actual use cases.

I have a production of two Gluster nodes with HDDs, now I plan to add SSDs to boost the overall performance.

**Comment by onlyjob** [comment]
1) Yes, I believe _dm-writeboost_ is mature enough for production.
I think author of _dm-writeboost_ is better qualified to answer design questions than me.

2)  It trust _dm-writeboost_ and I use it in production. I could not build enough confidence in (almost) unmaintained EnhanceIO to rely on it. I believe _dm-writeboost_ is more robust and it is well maintained. I've been using _dm-writeboost_ ever since its first release. There were only few issues in earlier versions that appears to be all fixed.

I use dm-writeboost with RAM disk as caching devices. 
As for Gluster I do not trust it due to lack of integrity checks...

**Comment by lanconnected** [comment]
Hi!
We are using enhanceio in writeback mode for more than a year in production. There were some stability issues hopefully resolved now, and we've never lost any data even after power losses/hard resets. We will support this branch and try to address any reported problem, but only for RHEL6/RHEL7 and OpenVZ kernels for now. dm-writeboost vs enhanceio discussion is probably out of topic here, they both have their pros and cons. If you use and enhanceio compiled from this fork and have any problem, please file the issue here, any feedback is welcome.

**Comment by samuelxhu** [comment]
@lanconnected This is great. Thanks a lot.
